version: '3.7'

services:

  db:
    image: postgres:12.0-alpine
    networks:
     - grafana-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  grafana:
    build: ./grafana
    #image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    networks:
      - grafana-network
    env_file:
      - ./.env.prod.grafana
    volumes:
       - grafana_storage:/var/lib/grafana grafana/grafana

volumes:
  postgres_data:
  grafana_storage:

networks:
 grafana-network: